config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'lists#index'
  resources :lists do
    resources :bookmarks, only: [:create, :new]
  end
  resources :bookmarks, only: [:destroy, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_one_attached :photo
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, :overview, uniqueness: true
  validates :title, presence: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render 'lists/show', status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @list.save
    redirect_to list_path(@list)
  end

  def show
    @list = List.find(params[:id])
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    @list = List.find(params[:id])
    if @list.update(list_params)
      redirect_to @list, notice: "Photo was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_path, notice: "List was successfully deleted."
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/new.html.erb
<h1>Add a movie</h1>
<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie %>
  <%= f.button :submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Dancing+Script&family=Open+Sans:wght@300;400;600&family=Raleway:wght@800&family=Roboto:wght@100;300;400&display=swap" rel="stylesheet">
  </head>

  <body>
  <%= render "shared/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/lists/edit.html.erb
<%= simple_form_for @list do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%= f.button :submit %>
<% end %>

app/views/lists/index.html.erb
<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://wordpress.wbur.org/wp-content/uploads/2020/12/GettyImages-1150049038-1000x630.jpg)">
  <p>Top Movies</p>
</div>
<div class="container">
<h2>My Lists</h2>
  <div class = "card-grid" >
    <% @lists.each do |list| %>
      <div class= "card-category" style= "background-image: url(<%= cl_image_path list.photo.key %>)">
        <div class="card-title">
          <h3><%= link_to list.name, list_path(list) %></h3>
        </div>
          <%= link_to edit_list_path(list) do %>
            <div class="update-icon"><i class="fa-solid fa-pen-to-square" style="color: #E6E6E6;"></i>
            <% end %>
            </div>
      </div>
    <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<h1>New list</h1>
<%= simple_form_for @list do |f| %>
  <%= f.input :name %>
  <%= f.button :submit %>
<% end %>

app/views/lists/show.html.erb
<div class="container">
  <h2><%= @list.name %></h2>
  <p class="btn btn-outline-secondary"><%= link_to "Create a bookmark", new_list_bookmark_path(@list) %></p>
  <div class="card-grid">
    <% @list.bookmarks.each do |bookmark|%>
    <div class="card-product">
      <img src="<%= bookmark.movie.poster_url %>" alt="<%= bookmark.movie.title %> Poster" />
      <div class="card-product-infos">
        <p><%= bookmark.comment %></p>
        <%= link_to bookmark_path(bookmark), data: {turbo_method: :delete, turbo_confirm: "Are you sure you want to delete?"} do %>
          <i class="fa-regular fa-trash-can" style="color: #000000;"></i>
        <% end %>
        </div>
      </div>
    <% end %>
    </div>
  <p><%= link_to "Return to my lists", lists_path %></p>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-container">
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
    <div class="container-nav">
      <%= link_to lists_path, class: "navbar-brand" do %>
        <%= image_tag "TheWatchList1.png" %>
        <div id="navbarSupportedContent">
          </a class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
            <%= link_to "Create a Movie List", new_list_path, class: "dropdown-items" %>
      <% end %>
      </div>
    </div>
  </div>
</div>